
-- customer
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Hide', '123 Fake Street', 'fake@gmail.com', '12345');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Jill', '361 Manhattan Rd', 'roesch@yahoo.ca', 'jJys3m');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Jim', '138 North Hall St', 'uqmcolyv@gmail.com', 'BZRfhD');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Singh', '436 Wild Rose Drive', 'itstatus@icloud.com', 'jYfPKf');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Ivan', '667 South Blackburn St', 'fhirsch@verizon.net', 'cKJWfA');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Thomas', '2420 Santa Fir Ct', 'tmoua3000@gmail.com', 'thx12345');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('James', '8577 South North Ave', 'alastair@msn.com', 'jb4sm7');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('John', '785 St Paul St', 'graham@sbcglobal.net', '2SBybj');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Robert', '78 Fairfield Lane', 'animats@outlook.com', 'Bjd2JK');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES('Michael', '7695 Baker Street', 'jmorris@hotmail.com', 'DGK2sA');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'William', '27 Vernon Street', 'garyjb@aol.com', 'WvYHYs');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'David', '220 Orchard Lane', 'presoff@verizon.net', 'AH9Y4K');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Richard', '6 Coffee St', 'moonlapse@yahoo.ca', 'K3qtDU');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jospeh', '3 Pineknoll Ave', 'tubesteak@aol.com', 'yr9Et3');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Charles', '933 Glenholme Street', 'aegreene@live.com', 'FpK7SK');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Chirstopher', '8746 Hilltop Street', 'joelw@mac.com', 'jNp4G8');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Daniel', '9784 Lake Forest Lane', 'joehall@att.net', 'HPxhGQ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Matthew', '9626 NW. Edgefield Street', 'hllam@comcast.net', 'kVrngH');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Anthony', '83 Maiden St', 'reeds@verizon.net', '2EXSfE');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Donald', '99C W. Temple Ave', 'gomor@optonline.net', 'yRN9Qu');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Mark', '7245 Joy Ridge Street', 'emmanuel@comcast.net', 'JkFWQn');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Paul', '7037 Marsh Dr', 'matthijs@optonline.net', 'vCK9DS');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Steven', '9126 Woodsman Court', 'nwiger@verizon.net', 'x3NgmZ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Andrew', '58 S. Elizabeth Street', 'syncnine@verizon.net', 'hnRdYP');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Kenneth', '578 Illinois St', 'hauma@optonline.net', 'YAKwXe');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Joshua', '966 Sunset Street', 'british@msn.com', 'gAFbsw');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Kevin', '9659 8th St', 'gavinls@yahoo.ca', 'zVSvNY');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Brian', '3 Saxon Street', 'benanov@icloud.com', 'KJkbcS');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'George', '9129 S. Galvin Street', 'tjensen@outlook.com', 'juFHUC');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Edward', '629 Pulaski Ave', 'lishoy@aol.com', '');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Ronald', '977 East School Street', 'hermanab@icloud.com', 'mKeu7r');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Timothy', '9566 West Elizabeth Circle', 'sassen@yahoo.ca', '3HpD5T');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jason', '820 Marsh Ave', 'dbanarse@icloud.com', 'Ap5HYp');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Gary', '282 Shady St', 'bogjobber@gmail.com', 'kZDnyT');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Nicholas', '9516 Courtland Circle', 'punkis@outlook.com', 'wv8ywD');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Eric', '364 Rockaway Dr', 'nullchar@outlook.com', 'TQhRa8');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jonathan', '989 Theatre Ave', 'bolow@yahoo.ca', 'HeVjHE');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Stephen', '594 Ivy St', 'timtroyr@icloud.com', 'SB39ru');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Justin', '10 Hudson Drive', 'dinther@gmail.com', 'NpM2a5');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Larry', '178 South Princeton St', 'andersbr@comcast.net', 'EYa4BN');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Scott', '31 Mill Pond Circle', 'marnanel@mac.com', 'AYSQk2');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Brandon', '676 Homewood Drive', 'cfhsoft@verizon.net', 'uTu83j');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Benjamin', '90 W. Harvey St', 'sonnen@hotmail.com', 'wpmNq7');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Samuel', '7 Old Harvey St', 'valdez@comcast.net', 'CfAB9q');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Frank', '8431 East Shadow Brook Rd', 'dunstan@live.com', 'Dat9nV');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Gregory', '7856 North St', 'staikos@sbcglobal.net', 'fMzEbe');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Raymond', '25 North St', 'shazow@outlook.com', 'y9HeaA');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Frank', '8769 Front Ave', 'curly@icloud.com', 'xGbNpJ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Alexander', '356 Marshall Drive', 'optonline', 'p7erVn');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Patrick', '47 Oak Meadow Road', 'natepuri@mac.com', 'vc4sKA');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jack', '74 River Court', 'carreras@sbcglobal.net', 'c4CyRG');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Dennis', '580 Arlington Street', 'garyjb@outlook.com', 'dNMfYL');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jerry', '7875 West Gregory Street', 'mgreen@verizon.net', 'U4p2pq');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Tyler', '721 N. Bohemia Ave', 'lauronen@att.net', 'ytuSuP');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Aaron', '112 Glen Creek Drive', 'ntegrity@msn.com', 'shb6PR');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jack', '511 Sutor Ave', 'parkes@msn.com', 'DdBCZg');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jose', '255 Homewood Ave', 'mfburgo@live.com', 'afHK4m');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Henry', '8231 East Proctor St', 'tezbo@outlook.com', 'wXKzeU');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Adam', '565 Airport St', 'benits@outlook.com', 'V85Wcf');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Douglas', '7654 Lakeshore Road', 'pplinux@msn.com', 'kUkBGQ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Nathan', '83 Division St', 'daveewart@live.com', 'kYcxqr');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Peter', '59 St Paul St', 'bartak@att.net', 'g74XkY');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Zachary', '8682 Bayberry Avenue', 'danzigism@aol.com', 'dFtvku');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Kyle', '408 Sierra Drive', 'dieman@verizon.net', 'ht2d9q');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Walter', '9088 Marsh Rd', 'pplinux@icloud.com', 'WnSYW7');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Harold', '222 East Victoria Street', 'leviathan@optonline.net', 'mcuqhd');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jeremy', '7557 Beechwood St', 'smartfart@optonline.net', 'UnsQxE');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Ethan', '7572 Grand Road', 'krueger@gmail.com', 'DYCj2p');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Carl', '9164 Prairie Ave', 'neonatus@aol.com', 'pHqALS');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Keith', '23 Cardinal St', 'dvdotnet@comcast.net', 'VEJeRk');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Sarah', '9599 King Ave', 'heroine@optonline.net', 'ZYWmL4');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Roger', '109 NW. Water Street ', 'drewf@comcast.net', 'AKsEYb');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Gerald', '8200 NE. Arcadia Lane', 'mxiao@hotmail.com', 'UQ3Hy6');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Chirstian', '6 Bay Meadows Lane', 'satishr@yahoo.com', 'eGZ5CG');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Terry', '9824 Cherry Drive', 'parasite@outlook.com', 'jSJxUJ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Sean', '70 W. Jackson Street', 'bartlett@verizon.net', 'VuP8J5');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Arthur', '7557 Penn Street', 'qrczak@mac.com', 'Zgphmj');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Austin', '658 Summit Dr.', 'jguyer@me.com', 'xqMS4p');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Noah', '323 Pendergast Dr.', 'kuparine@outlook.com', 'FFCSNp');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Lawrence', '8067 Green Lake Street', 'miami@sbcglobal.net', 'UxK4A2');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jesse', '200 S. Paris Hill Ave', 'rafasgj@icloud.com', 'HRgj4F');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Joe', '945 Glenridge Drive', 'inico@yahoo.ca', '4bctfr');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Bryan', '588 Talbot St', 'pkilab@comcast.net', '8fSvm4');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Billy', '93 West Inverness Circle', 'amimojo@comcast.net', 'b2cau2');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Jordan', '2 Oak Valley Ave', 'paley@live.com', 'M8Etcj');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'ALbert', '92 Madison Dr', 'techie@optonline.net', 'JNbBkw');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Dylan', '984 Lancaster Dr', 'jandrese@yahoo.com', 'pCFLgE');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Bruce', '135 S. 4th Dr', 'north@sbcglobal.net', 'Gt36tp');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Willie', '8778A Harvey Street', 'darin@live.com', 'sttZpb');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Gabriel', '19 Sycamore St', 'rbarreira@verizon.net', 'tNvgpy');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Alan', '984 Gonzales St', 'crypt@outlook.com', 'LMAxjA');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Juan', '90 East Armstrong Road', 'thomasj@optonline.net', 'gkDCWd');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Logan', '7055 Olive Drive', 'sopwith@msn.com', 'ngu6qX');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Wayne', '394 10th St', 'kassiesa@outlook.com', 'vpWPDQ');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Ralph', '5 Sleepy Hollow Ave. ', 'retoh@comcast.net', 'srFRgK');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Roy', '82 E. Strawberry St', 'rmcfarla@outlook.com', 'wWUfES');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Eugene', '50 Sycamore Street', 'sfoskett@outlook.com', 'LdwnCv');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Randy', '615 Wakehurst St', 'jmmuller@yahoo.ca', '5wZjah');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Vincent', '64 Randall Mill St', 'horrocks@yahoo.com', 'u7SDqn');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Russell', '148 Shadow Brook Street', 'jkegl@gmail.com', 'A5EMPk');
INSERT INTO customer(ct_name,ct_address,ct_email,ct_password) VALUES( 'Louis', '963 Hamilton Ave', 'feamster@sbcglobal.net', '57a9E4');